---
namespace: "tcharl"
name: "bind9"
version: "1.0.1"
description: "Configures and runs (containerized) bind9 DNS server and configured it on clients"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/bind9"
documentation: "https://github.com/OsgiliathEnterprise/bind9/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/bind9"
issues: "https://github.com/OsgiliathEnterprise/bind9/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "freeipa"
  - "freeipa-server"
