---
- name: Dns_client | retrieve masters ip
  community.docker.docker_container_info:
    name: "bind9"
  become: true
  register: dnsmasterssetup
  delegate_facts: true
  delegate_to: "{{ groups[bind_masters_group][0] }}"

- name: Dns_client | debug masters ip
  ansible.builtin.debug:
    msg: "{{ dnsmasterssetup }}"
    verbosity: 2

- name: Dns_client | compute master ip if preferred_nic is not set
  ansible.builtin.debug:
    msg: "{{ dnsmasterssetup.container.NetworkSettings.IPAddress }}"
  register: dns_master_ip

- name: Dns_client | create resolved.conf.d directory
  become: true
  ansible.builtin.file:
    state: directory
    dest: '/etc/systemd/resolved.conf.d'
    mode: "0755"

- name: Dns_client | add internal domain dns
  ansible.builtin.template:
    src: systemd-resolved.conf.d/head.j2
    dest: /etc/systemd/resolved.conf.d/head.conf
    owner: root
    group: root
    mode: 0644
  become: true
  vars:
    dns_master_ip_to_set: "{{ dns_master_ip.msg }}"
    domain: "{{ company_domain }}"
  notify:
    - ansible-nameserver | reload bind

- name: Dns_client | restarts systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  changed_when: false
  become: true
