---

- name: Install | configure firewalld
  ansible.builtin.include_role:
    name: tcharl.ansible_routing
  vars:
    firewalld_zones:
      - name:  "{{ firewalld_zone }}"
        masquerade: true
        enabled_services:
          - service: dns
  tags:
    - dependency

- name: Install | stops firewalld
  become: true
  changed_when: false
  ansible.builtin.service:
    name: firewalld
    state: stopped

- name: Install | restarts dockerd
  become: true
  changed_when: false
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Install | disables resolved-conf loopback
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    insertafter: '^#DNSStubListener=yes'
    regexp: 'DNSStubListener=no'
    line: 'DNSStubListener=no'
  become: yes

- name: Install | restarts systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  changed_when: false
  become: true

- name: Install | bind9 server
  community.general.docker_container:
    name: bind9
    image: fike/bind9
    restart_policy: "always"
    published_ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - "{{ bind_conf_dir }}/named.conf.local:/etc/bind/named.conf.local"
      - "{{ bind_conf_dir }}/named.conf.options:/etc/bind/named.conf.options"
      - "{{ bind_zones_dir }}:{{ bind_zones_docker_dir }}"
    state: started
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep ':53 ' > /dev/null; if [ 0 != $? ]; then exit 1; fi;"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 6s
  become: true

- name: Install | starts firewalld
  become: true
  changed_when: false
  ansible.builtin.service:
    name: firewalld
    state: started
