---
# tasks file for ansible-users

- name: Prerequisites
  ansible.builtin.include_tasks: prereq.yml

- name: Role facts
  ansible.builtin.include_tasks: role_facts.yml

- name: Requirements
  ansible.builtin.import_tasks: requirements.yml
  when:
    - standalone_role
    - (
        bind_masters_group in group_names
      ) or
      (
        bind_slaves_group in group_names
      )

- name: Bind server configuration
  ansible.builtin.include_tasks: config_bind.yml
  when: >
    (
    (
    bind_masters_group in group_names
    ) or
    (
    bind_slaves_group in group_names
    )
    ) and
    bind_config

- name: Bind server zone configuration
  ansible.builtin.include_tasks: manage_zones.yml
  when: >
    (
    bind_masters_group in group_names
    ) or
    (
    bind_slaves_group in group_names
    )
    and
    bind_manage_zones

- name: Install
  ansible.builtin.include_tasks: install.yml
  when: >
    (
    bind_masters_group in group_names
    ) or
    (
    bind_slaves_group in group_names
    )

- name: Dns client configuration
  ansible.builtin.include_tasks: dns_client.yml
  when: bind_clients in group_names
