---
- name: Manage_zones | create serial timestamp
  ansible.builtin.command: "date +%y%m%d%H" # a mix behind idempotence and acceptable human pause
  register: bind_timestamp
  changed_when: false

- name: Manage_zones | configuring bind zones
  ansible.builtin.template:
    src: etc/bind/named.conf.local.j2
    dest: "{{ bind_conf_dir }}/named.conf.local"
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - ansible-nameserver | reload bind

- name: Manage_zones | ensuring {{ bind_zones_dir }} exists
  ansible.builtin.file:
    path: "{{ bind_zones_dir }}"
    state: directory
    mode: 0755
  become: true
  when: bind_masters_group in group_names

- name: Manage_zones | bind directory
  ansible.builtin.file:
    path: "{{ bind_zones_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Manage_zones | creating forward zones
  ansible.builtin.template:
    src: etc/bind/zones/forward_zone.j2
    dest: "{{ bind_zones_dir + '/db.' + item['zone'] }}"
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - ansible-nameserver | reload bind
  with_items: "{{ bind_forward_zones }}"
  when: bind_masters_group in group_names

- name: Manage_zones | creating reverse zones
  ansible.builtin.template:
    src: etc/bind/zones/reverse_zone.j2
    dest: "{{ bind_zones_dir + '/db.' + item['zone'] }}"
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - ansible-nameserver | reload bind
  with_items: "{{ bind_reverse_zones }}"
  when: bind_masters_group in group_names
